project:
  type: website

website:
  title: "blog"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "fastai"
        contents:
          - lessons/01_what_is_that.ipynb
      - section: "blog"
        contents:
          - myblog/2_first_post.ipynb
      
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



